-- Seed project_projects depuis site_govgenz/projects-govgenz (FR) + database/project_seed_en (EN).
-- Même translation_group (slug FR) pour lier les paires FR/EN.
-- Prérequis : migrations appliquées (table project_projects + table sectors avec codes en minuscules).
-- Charset : utf8mb4.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM project_projects WHERE locale IN ('fr', 'en') AND slug IN ('connectez-ecoles', 'agrotech-jeunesse', 'eau-potable-2026', 'energie-solaire', 'acces-justice', 'sante-maternelle');

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'connectez-ecoles',
  'fr',
  'connectez-ecoles',
  '🎓 Connectez Écoles Madagascar',
  'Connectivité internet et énergie solaire pour 500 écoles rurales, avec formation des enseignants au numérique éducatif.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 Le problème","heading_style":"warm","intro":"Madagascar affiche l''un des taux d''accès au numérique scolaire les plus bas d''Afrique. 67 % des écoles rurales fonctionnent sans électricité, rendant tout équipement technologique inutilisable. Pendant ce temps, les plans gouvernementaux financent des tablettes qui resteront dans des caisses.","bullets":["67 % des écoles rurales sans électricité (source : MENB 2025)","14 % seulement de couverture internet nationale","82 % des enseignants du primaire sans formation numérique","Fracture numérique croissante entre urbain et rural","Plans publics qui équipent sans infrastructurer — dépense sans impact"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Notre solution","heading_style":"teal","intro":"GoV Gen Z Madagascar propose une approche en 3 piliers séquencés : d''abord l''infrastructure, ensuite les outils, enfin la formation. Pas de tablettes sans électricité.","bullets":["Pilier 1 — Électrification solaire : panels solaires off-grid pour 500 écoles, priorité DIANA, SAVA, ATSIMO ANDREFANA","Pilier 2 — Connectivité : 4G ou fibre selon la zone, avec routeurs robustifiés pour milieu rural","Pilier 3 — Formation pédagogique : 15 000 enseignants formés en 24 mois, partenariat universités locales + diaspora tech"],"extra_paragraphs":["Chaque école reçoit un kit complet (énergie + connexion + contenus locaux) et un enseignant référent formé. Un tableau de bord public suit l''avancement en temps réel."]},{"type":"budget_table","section_title":"💰 Budget détaillé","rows":[{"poste":"Électrification solaire","detail":"500 kits solaires off-grid, installation, maintenance 2 ans","montant":"400 000 000","row_class":""},{"poste":"Connectivité","detail":"500 connexions 4G\\/fibre, routeurs, abonnements 30 mois","montant":"250 000 000","row_class":""},{"poste":"Formation enseignants","detail":"15 000 enseignants × 3 jours de formation + matériel","montant":"120 000 000","row_class":""},{"poste":"Plateforme & contenus","detail":"Développement plateforme, contenus en malgache, hébergement","montant":"50 000 000","row_class":""},{"poste":"Suivi & évaluation","detail":"Tableau de bord public, audits trimestriels, rapports","montant":"30 000 000","row_class":""},{"poste":"TOTAL","detail":"","montant":"850 000 000","row_class":"total"}],"footnote":"Financement recherché : PTF, bailleurs bilatéraux, fonds diaspora. Budget validé par l''équipe Finances GoV Gen Z — audit indépendant planifié T3 2026."},{"type":"timeline","section_title":"📅 Calendrier","phases":[{"phase_label":"Phase 1","duration":"0 – 8 mois","step_title":"Pilote — 50 écoles région DIANA","body":"Installation des kits solaires, connexion 4G, formation 500 enseignants pilotes. Collecte des données de référence pour mesurer l''impact. Rapport public à M+8."},{"phase_label":"Phase 2","duration":"8 – 20 mois","step_title":"Déploiement — 250 écoles supplémentaires","body":"Extension vers SAVA, ATSIMO ANDREFANA, BETSIBOKA. Formation 7 500 enseignants supplémentaires. Lancement du tableau de bord public."},{"phase_label":"Phase 3","duration":"20 – 30 mois","step_title":"Finalisation — 200 écoles restantes + évaluation","body":"Couverture des 200 dernières écoles, formation des 7 000 enseignants restants, évaluation d''impact indépendante, publication du rapport final."}]},{"type":"kpi_grid","section_title":"📊 Indicateurs d''impact","heading_style":"teal","items":[{"value":"500","label":"Écoles connectées"},{"value":"15 000","label":"Enseignants formés"},{"value":"300 000","label":"Élèves bénéficiaires"},{"value":"10","label":"Régions couvertes"},{"value":"+40 %","label":"Résultats scolaires visés"},{"value":"100 %","label":"Audits publics"}]},{"type":"impact_tracker","section_title":"🎯 Suivi d''impact — Résultats actuels","heading_style":"teal","note":"Données au 12 mai 2026 · Phase 1 en cours · Mise à jour mensuelle","rows":[{"label":"Phase 1 — avancement","numbers":"38 % de la phase","bar_percent":38},{"label":"Écoles connectées","numbers":"15 \\/ 500","bar_percent":3},{"label":"Enseignants formés","numbers":"750 \\/ 15 000","bar_percent":5},{"label":"Budget activé","numbers":"120 M \\/ 850 M Ar","bar_percent":14},{"label":"Financement mobilisé","numbers":"14 % du budget","bar_percent":14}]},{"type":"team","section_title":"👥 Équipe projet","members":[{"name":"[Chef de projet — à renseigner]","role":"Coordination générale · Équipe Education"},{"name":"[Lead technique — à renseigner]","role":"Infrastructure solaire & connectivité · Équipe Digital"},{"name":"[Responsable formation — à renseigner]","role":"Programme enseignants · Partenariats universités"},{"name":"+ 124 volontaires actifs","role":"Terrain, logistique, formation, communication"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["MENB 2025 : Rapport national sur l''accès aux infrastructures scolaires","INSTAT 2024 : Données couverture internet par région","Concept note : Disponible sur demande — projets@govgenz.org","Budget détaillé : Fichier Excel disponible sur demande PTF","Rapport pilote : À publier M+8 (novembre 2026)"]}]',
  'actif',
  'published',
  'education,digital',
  127,
  '850 M Ar',
  '10 régions',
  '2026-03-01',
  30,
  38,
  '🎓 Connectez Écoles Madagascar',
  'Connectez Écoles Madagascar — Connectivité et énergie solaire pour 500 écoles rurales. GoV Gen Z Madagascar.',
'2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'connectez-ecoles',
  'en',
  'connectez-ecoles',
  '🎓 Connect Schools Madagascar',
  'Internet connectivity and solar power for 500 rural schools, with teacher training in digital education.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 The challenge","heading_style":"warm","intro":"Madagascar has one of the lowest rates of digital access in schools in Africa. 67% of rural schools have no electricity, so any technology investment sits unused. Meanwhile, public plans often fund devices without infrastructure.","bullets":["67% of rural schools without electricity (illustrative baseline)","14% national internet coverage (illustrative)","82% of primary teachers without digital training (illustrative)","Growing urban–rural digital divide"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Our approach","heading_style":"teal","intro":"GoV Gen Z Madagascar sequences three pillars: first infrastructure, then tools, then training. No tablets without power.","bullets":["Pillar 1 — Solar electrification: off-grid solar for 500 schools, priority regions","Pillar 2 — Connectivity: 4G or fibre where feasible, hardened routers for rural sites","Pillar 3 — Teacher training: 15,000 teachers over 24 months, local universities + diaspora tech partners"],"extra_paragraphs":[]},{"type":"budget_table","section_title":"💰 Budget overview","rows":[{"poste":"Solar electrification","detail":"500 off-grid kits, installation, 2-year maintenance","montant":"400 000 000","row_class":""},{"poste":"Connectivity","detail":"500 links, routers, 30-month subscriptions","montant":"250 000 000","row_class":""},{"poste":"Teacher training","detail":"15,000 teachers × 3 days + materials","montant":"120 000 000","row_class":""},{"poste":"TOTAL (illustrative)","detail":"","montant":"850 000 000","row_class":"total"}],"footnote":""},{"type":"kpi_grid","section_title":"📊 Impact snapshot","heading_style":"teal","items":[{"value":"500","label":"Schools targeted"},{"value":"15 000","label":"Teachers trained"},{"value":"10","label":"Regions"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["Concept note: on request — projets@govgenz.org"]}]',
  'actif',
  'published',
  'education,digital',
  127,
  '850 M Ar',
  '10 regions',
  '2026-03-01',
  30,
  38,
  '🎓 Connect Schools Madagascar',
  'Connect Schools Madagascar — connectivity and solar power for 500 rural schools. GoV Gen Z Madagascar.',
'2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'agrotech-jeunesse',
  'fr',
  'agrotech-jeunesse',
  '🌾 Agrotech Jeunesse',
  'Former 1 000 jeunes agriculteurs avec technologies durables, semences améliorées et accès direct aux marchés via une plateforme digitale.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 Le problème","heading_style":"warm","intro":"Madagascar consacre 70 % de sa population active à l''agriculture, mais reste structurellement dépendant des importations alimentaires. Les jeunes ruraux quittent l''agriculture faute d''accès aux techniques modernes, aux marchés et à un revenu décent. Le secteur vieillit pendant que la jeunesse cherche Antananarivo.","bullets":["70 % de la population active dans l''agriculture (INSTAT 2024)","48 % des ménages ruraux en insécurité alimentaire (FAO 2025)","Rendements du riz 2× inférieurs à la moyenne sub-saharienne","Moins de 8 % des jeunes de 18-35 ans restent en agriculture rurale","Accès quasi nul aux marchés d''exportation et prix garantis"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Notre solution","heading_style":"teal","intro":"Agrotech Jeunesse forme des jeunes agriculteurs en combinant savoir technique, outils numériques et débouchés commerciaux garantis. Pas de formation déconnectée du terrain — chaque module est ancré dans des résultats mesurables.","bullets":["Pilier 1 — Formation agronomique : 6 mois de formation en techniques durables (SRI, agroforesterie, compostage), semences certifiées, et gestion des intrants","Pilier 2 — Outils numériques : Application mobile MahasaFarm (météo agricole, prix marché, conseils agronomiques), tablettes subventionnées pour les groupements","Pilier 3 — Marché garanti : Plateforme de mise en relation directe producteurs-acheteurs, contrats avec restaurateurs et exportateurs, fonds de garantie prix plancher"],"extra_paragraphs":["Les 1 000 jeunes formés deviennent des \\"agrotech leaders\\" dans leurs communes — chacun transmet ensuite les techniques à 5 autres agriculteurs de son entourage."]},{"type":"budget_table","section_title":"💰 Budget détaillé","rows":[{"poste":"Formation agronomique","detail":"1 000 jeunes × 6 mois, formateurs, centres de formation","montant":"150 000 000","row_class":""},{"poste":"Semences & intrants","detail":"Semences améliorées certifiées + kits de démarrage par participant","montant":"80 000 000","row_class":""},{"poste":"Application MahasaFarm","detail":"Développement, maintenance 2 ans, hébergement, 1 000 licences","montant":"60 000 000","row_class":""},{"poste":"Équipement numérique","detail":"200 tablettes pour groupements + subvention data mobile","montant":"55 000 000","row_class":""},{"poste":"Plateforme marché","detail":"Développement plateforme, mise en relation, fonds prix plancher","montant":"50 000 000","row_class":""},{"poste":"Suivi & évaluation","detail":"Monitoring terrain, audits semestriels, rapport d''impact","montant":"25 000 000","row_class":""},{"poste":"TOTAL","detail":"","montant":"420 000 000","row_class":"total"}],"footnote":"Co-financement visé : FIDA, FAO, Union Européenne (fonds développement rural). Budget validé équipe Finance GoV Gen Z."},{"type":"timeline","section_title":"📅 Calendrier","phases":[{"phase_label":"Phase 1","duration":"0 – 6 mois","step_title":"Pilote — 200 jeunes, Vakinankaratra","body":"Sélection et formation de la première cohorte. Test de l''application MahasaFarm. Signature des premiers contrats marché garanti. Rapport d''étape à M+6."},{"phase_label":"Phase 2","duration":"6 – 16 mois","step_title":"Extension — 600 jeunes supplémentaires","body":"Déploiement vers Itasy et Bongolava. Lancement de la plateforme marché. Premières récoltes avec revenus garantis mesurés. Publication des résultats."},{"phase_label":"Phase 3","duration":"16 – 24 mois","step_title":"Finalisation — 200 derniers participants + évaluation","body":"Formation des 200 derniers participants. Activation du réseau \\"agrotech leaders\\" pour transmission aux 5 000 agriculteurs entourage. Évaluation d''impact finale."}]},{"type":"kpi_grid","section_title":"📊 Indicateurs d''impact","heading_style":"teal","items":[{"value":"1 000","label":"Jeunes formés"},{"value":"5 000","label":"Agriculteurs en cascade"},{"value":"+60 %","label":"Rendement visé"},{"value":"3 régions","label":"Couverture géographique"},{"value":"+80 %","label":"Revenu agricole visé"},{"value":"100 %","label":"Audits publics"}]},{"type":"impact_tracker","section_title":"🎯 Suivi d''impact — Résultats actuels","heading_style":"teal","note":"Données au 12 mai 2026 · Phase 1 en cours · Mise à jour mensuelle","rows":[{"label":"Phase 1 — avancement","numbers":"55 % de la phase","bar_percent":55},{"label":"Jeunes agriculteurs formés","numbers":"110 \\/ 1 000","bar_percent":11},{"label":"Utilisateurs app MahasaFarm","numbers":"95 \\/ 1 000","bar_percent":10},{"label":"Hausse rendement (pilote)","numbers":"+38 % \\/ obj. +60 %","bar_percent":63},{"label":"Budget activé","numbers":"105 M \\/ 420 M Ar","bar_percent":25}]},{"type":"team","section_title":"👥 Équipe projet","members":[{"name":"[Chef de projet — à renseigner]","role":"Coordination générale · Équipe Food"},{"name":"[Lead agronomique — à renseigner]","role":"Formation technique, partenariats instituts agronomiques"},{"name":"[Lead digital — à renseigner]","role":"Application MahasaFarm · Équipe Digital"},{"name":"+ 86 volontaires actifs","role":"Terrain, formation, logistique, suivi marché"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["INSTAT 2024 : Enquête nationale emploi et agriculture","FAO 2025 : Rapport sécurité alimentaire Madagascar","MAEP : Données rendements céréales par région","Concept note : Disponible sur demande — projets@govgenz.org","Budget détaillé : Fichier Excel disponible sur demande PTF","Rapport pilote : À publier M+6 (juillet 2026)"]}]',
  'actif',
  'published',
  'food,economy',
  89,
  '420 M Ar',
  'Vakinankaratra',
  '2026-01-01',
  24,
  55,
  '🌾 Agrotech Jeunesse',
  'Agrotech Jeunesse — Former 1 000 jeunes agriculteurs avec technologies durables. GoV Gen Z Madagascar.',
'2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'agrotech-jeunesse',
  'en',
  'agrotech-jeunesse',
  '🌾 Agrotech Youth',
  'Train 1,000 young farmers with sustainable techniques, improved seed, and direct market access through a digital platform.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 The challenge","heading_style":"warm","intro":"Most of Madagascar’s workforce depends on agriculture, yet productivity and youth retention in rural farming remain low. Young people leave farming without access to modern techniques, markets, or fair income.","bullets":["Low yields compared with regional benchmarks","Limited access to export markets and stable prices","Weak digital tools for weather, prices, and agronomy"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Our approach","heading_style":"teal","intro":"Agrotech Youth combines agronomy, digital tools, and guaranteed market linkages. Every module ties to measurable outcomes.","bullets":["Pillar 1 — Agronomy training: sustainable techniques, certified seed, input management","Pillar 2 — Digital tools: mobile app for weather, market prices, and advice; tablets for cooperatives","Pillar 3 — Market access: direct buyer matching, contracts, floor-price guarantee fund"],"extra_paragraphs":[]},{"type":"budget_table","section_title":"💰 Budget overview","rows":[{"poste":"Agronomy training","detail":"1,000 young farmers × 6 months","montant":"150 000 000","row_class":""},{"poste":"Seed & inputs","detail":"Certified seed and starter kits","montant":"80 000 000","row_class":""},{"poste":"Mobile platform","detail":"Development, hosting, licences","montant":"60 000 000","row_class":""},{"poste":"TOTAL (illustrative)","detail":"","montant":"420 000 000","row_class":"total"}],"footnote":""},{"type":"kpi_grid","section_title":"📊 Impact snapshot","heading_style":"teal","items":[{"value":"1 000","label":"Youth trained"},{"value":"3","label":"Regions"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["Concept note: on request — projets@govgenz.org"]}]',
  'actif',
  'published',
  'food,economy',
  89,
  '420 M Ar',
  'Vakinankaratra',
  '2026-01-01',
  24,
  55,
  '🌾 Agrotech Youth',
  'Agrotech Youth — train 1,000 young farmers with sustainable tech, improved seed, and market access. GoV Gen Z Madagascar.',
'2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'eau-potable-2026',
  'fr',
  'eau-potable-2026',
  '💧 Eau Potable 2026',
  'Construction de 50 points d''eau potable dans les Hauts Plateaux avec formation locale en maintenance et gouvernance communautaire.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 Le problème","heading_style":"warm","intro":"Dans les Hauts Plateaux de Madagascar, 63 % des ménages ruraux n''ont pas accès à l''eau potable. Les femmes et enfants parcourent en moyenne 4 km par jour pour aller chercher de l''eau, au détriment de la scolarisation et de la productivité. Les maladies hydriques représentent 28 % des hospitalisations en zone rurale.","bullets":["63 % des ménages ruraux des Hauts Plateaux sans eau potable (JIRAMA 2024)","4 km de trajet moyen quotidien pour l''eau (WASH Madagascar 2024)","28 % des hospitalisations liées aux maladies hydriques (Ministère Santé 2025)","Taux de mortalité infantile × 3 dans les zones sans eau sécurisée","Points d''eau existants : 40 % hors service faute de maintenance locale formée"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Notre solution","heading_style":"teal","intro":"Eau Potable 2026 ne construit pas seulement des forages — il construit des systèmes durables. Chaque point d''eau est accompagné d''une gouvernance communautaire et d''une équipe formée à la maintenance.","bullets":["Pilier 1 — Construction : 50 forages équipés de pompes manuelles robustifiées pour milieu rural, avec bassins de décantation et clôtures de protection sanitaire","Pilier 2 — Maintenance locale : 2 techniciens locaux formés par point d''eau (100 personnes au total) avec kit d''outils et guide de maintenance en malgache","Pilier 3 — Gouvernance communautaire : Comité de gestion de l''eau élu par commune, cotisation communautaire pour fond de maintenance, suivi de la qualité mensuel"],"extra_paragraphs":["Un tableau de bord numérique simple (SMS + web) permet de signaler les pannes et suivre l''état des 50 points d''eau en temps réel."]},{"type":"budget_table","section_title":"💰 Budget détaillé","rows":[{"poste":"Forage & équipement","detail":"50 forages × coût moyen (pompe, dalle, clôture)","montant":"175 000 000","row_class":""},{"poste":"Formation maintenance","detail":"100 techniciens locaux × 5 jours + kits outils","montant":"35 000 000","row_class":""},{"poste":"Gouvernance communautaire","detail":"Formation comités, guides malgaches, ateliers","montant":"20 000 000","row_class":""},{"poste":"Analyse qualité eau","detail":"Tests qualité initiaux + 2 campagnes de contrôle annuelles","montant":"25 000 000","row_class":""},{"poste":"Suivi numérique","detail":"Tableau de bord SMS\\/web, maintenance 18 mois","montant":"15 000 000","row_class":""},{"poste":"Logistique & études terrain","detail":"Études hydrogéologiques préalables, transport, coordination","montant":"10 000 000","row_class":""},{"poste":"TOTAL","detail":"","montant":"280 000 000","row_class":"total"}],"footnote":"Financement visé : UNICEF WASH, AFD, partenaires bilatéraux. Dossier en cours de finalisation — validation prévue Q3 2026."},{"type":"timeline","section_title":"📅 Calendrier","phases":[{"phase_label":"Phase 0","duration":"Maintenant – 2 mois","step_title":"Validation du dossier candidat","body":"Instruction du dossier par l''équipe GoV Gen Z, études hydrogéologiques préliminaires, identification des 50 sites prioritaires avec les communes partenaires."},{"phase_label":"Phase 1","duration":"M+2 – M+10","step_title":"Construction — 25 premiers forages","body":"Forage, équipement, dalles de protection. Formation des 50 premiers techniciens locaux. Mise en place des comités de gestion. Rapport intermédiaire public."},{"phase_label":"Phase 2","duration":"M+10 – M+18","step_title":"Construction — 25 forages restants + évaluation","body":"Déploiement des 25 derniers points d''eau. Formation des 50 techniciens restants. Évaluation d''impact indépendante. Publication rapport final."}]},{"type":"kpi_grid","section_title":"📊 Indicateurs d''impact","heading_style":"teal","items":[{"value":"50","label":"Points d''eau construits"},{"value":"25 000","label":"Ménages bénéficiaires"},{"value":"100","label":"Techniciens formés"},{"value":"-60 %","label":"Maladies hydriques visées"},{"value":"-4 km","label":"Trajet quotidien économisé"},{"value":"100 %","label":"Gouvernance communautaire"}]},{"type":"note_panel","section_title":"🎯 Suivi d''impact","heading_style":"teal","message":"📊 Le suivi d''impact sera activédès le démarrage officiel du projet. Statut actuel : en attente de validation","submessage":""},{"type":"team","section_title":"👥 Équipe projet","members":[{"name":"[Chef de projet — à renseigner]","role":"Coordination générale · Équipe Water"},{"name":"[Expert hydrogéologue — à renseigner]","role":"Études terrain, sélection sites, supervision technique"},{"name":"[Responsable communautaire — à renseigner]","role":"Formation comités de gestion · Équipe Territories"},{"name":"+ 42 volontaires actifs","role":"Terrain, suivi qualité, formation, communication"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["JIRAMA 2024 : Rapport accès eau potable par région","WASH Madagascar 2024 : Données distance collecte eau","Ministère de la Santé 2025 : Rapport maladies hydriques","Concept note : Disponible sur demande — projets@govgenz.org","Budget détaillé : Fichier Excel disponible sur demande PTF","Rapport démarrage : À publier M+2 (dès validation)"]}]',
  'candidat',
  'draft',
  'water,health',
  45,
  '280 M Ar',
  'Hauts Plateaux',
  '2026-04-01',
  18,
  0,
  '💧 Eau Potable 2026',
  'Eau Potable 2026 — 50 points d''eau potable dans les Hauts Plateaux. GoV Gen Z Madagascar.',
NULL,
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'eau-potable-2026',
  'en',
  'eau-potable-2026',
  '💧 Drinking Water 2026',
  'Build 50 safe water points in the Central Highlands with local maintenance training and community governance.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 The challenge","heading_style":"warm","intro":"In the Central Highlands, many rural households still lack reliable access to safe drinking water. Long daily walks to fetch water affect schooling and productivity; waterborne disease burden remains high.","bullets":["Distance and time cost for water collection","Existing points often fall out of service without trained maintenance","Need for community governance and quality monitoring"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Our approach","heading_style":"teal","intro":"We build durable systems, not one-off boreholes: each point includes local maintenance capacity and a water committee.","bullets":["Pillar 1 — Construction: 50 equipped boreholes with hand pumps, protection, fencing","Pillar 2 — Local maintenance: two trained technicians per point (100 people total) with toolkits","Pillar 3 — Governance: elected committees, small maintenance fund, monthly quality checks"],"extra_paragraphs":[]},{"type":"budget_table","section_title":"💰 Budget overview","rows":[{"poste":"Boreholes & equipment","detail":"50 sites, pumps, slabs, fencing","montant":"175 000 000","row_class":""},{"poste":"Maintenance training","detail":"100 technicians × 5 days + toolkits","montant":"35 000 000","row_class":""},{"poste":"TOTAL (illustrative)","detail":"","montant":"280 000 000","row_class":"total"}],"footnote":""},{"type":"note_panel","section_title":"🎯 Impact tracking","heading_style":"teal","message":"📊 Impact tracking will startonce the project is officially launched. Current status: candidate \\/ pending validation","submessage":""},{"type":"sources","section_title":"📎 Sources & documents","lines":["Concept note: on request — projets@govgenz.org"]}]',
  'candidat',
  'draft',
  'water,health',
  45,
  '280 M Ar',
  'Central Highlands',
  '2026-04-01',
  18,
  0,
  '💧 Drinking Water 2026',
  'Drinking Water 2026 — 50 safe water points in the Central Highlands with local maintenance and community governance. GoV Gen Z Madagascar.',
NULL,
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'energie-solaire',
  'fr',
  'energie-solaire',
  '⚡ Énergie Solaire Communautaire',
  '200 mini-grids solaires en zones isolées pour créer des emplois locaux et réduire les émissions de CO₂ de manière mesurable.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 Le problème","heading_style":"warm","intro":"Madagascar présente l''un des taux d''électrification les plus bas du monde. 75 % de la population n''a pas accès à l''électricité, un chiffre qui monte à 92 % en zones rurales isolées. Les groupes électrogènes à gasoil sont la seule alternative — coûteux, polluants et fragiles logistiquement.","bullets":["75 % de la population sans électricité (Banque Mondiale 2024)","92 % des zones rurales isolées sans accès réseau JIRAMA","Le gasoil représente 60-80 % des coûts opérationnels des PME rurales","Cliniques rurales sans réfrigération pour vaccins — chaîne du froid brisée","Madagascar parmi les pays les plus exposés aux impacts du changement climatique"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Notre solution","heading_style":"teal","intro":"Chaque mini-grid solaire est dimensionné pour alimenter un village entier — habitations, école, dispensaire, commerces. Pas de solution ponctuelle : une infrastructure durable avec maintenance locale.","bullets":["Pilier 1 — Infrastructure mini-grid : 200 micro-réseaux solaires avec batteries lithium, câblage de distribution basse tension, compteurs prépayés par ménage","Pilier 2 — Emplois locaux : 400 techniciens énergétiques formés (2 par village), certifiés, salariés par le comité de gestion communautaire","Pilier 3 — Gouvernance & financement : Système de paiement mobile M-Cash pour les abonnements, fonds de renouvellement alimenté par les cotisations, audit annuel des émissions évitées"],"extra_paragraphs":["Chaque mini-grid est conçu pour une durée de vie de 20 ans. Les émissions de CO₂ évitées sont documentées pour valorisation carbone."]},{"type":"budget_table","section_title":"💰 Budget détaillé","rows":[{"poste":"Équipement solaire","detail":"200 mini-grids (panneaux, batteries, onduleurs, câblage)","montant":"600 000 000","row_class":""},{"poste":"Installation & génie civil","detail":"Structures, pylônes, câblage distribution, connexions ménages","montant":"150 000 000","row_class":""},{"poste":"Formation techniciens","detail":"400 techniciens × 3 mois de formation + certification","montant":"80 000 000","row_class":""},{"poste":"Système paiement mobile","detail":"Intégration M-Cash, compteurs prépayés, maintenance 3 ans","montant":"40 000 000","row_class":""},{"poste":"Gouvernance communautaire","detail":"Formation comités, guides, ateliers, fonds de renouvellement initial","montant":"30 000 000","row_class":""},{"poste":"Suivi & mesure CO₂","detail":"Monitoring émissions, audit annuel, rapport carbone","montant":"20 000 000","row_class":""},{"poste":"TOTAL","detail":"","montant":"920 000 000","row_class":"total"}],"footnote":"Financement visé : Green Climate Fund, AFD énergie, partenaires bilatéraux. Valorisation carbone prévue pour autofinancement partiel des phases 2 et 3."},{"type":"timeline","section_title":"📅 Calendrier","phases":[{"phase_label":"Phase 1","duration":"0 – 10 mois","step_title":"Pilote — 40 mini-grids, région DIANA","body":"Déploiement des 40 premiers mini-grids dans les communes les plus isolées de DIANA. Formation des 80 premiers techniciens. Lancement du système M-Cash. Mesure initiale des émissions évitées. Rapport public à M+10."},{"phase_label":"Phase 2","duration":"10 – 24 mois","step_title":"Extension — 100 mini-grids supplémentaires","body":"Déploiement vers ATSIMO ANDREFANA et ANDROY. Formation des 200 techniciens supplémentaires. Publication du premier rapport d''impact et de la valorisation carbone."},{"phase_label":"Phase 3","duration":"24 – 36 mois","step_title":"Finalisation — 60 derniers mini-grids + évaluation","body":"Couverture des 60 derniers villages. Formation des 120 techniciens restants. Évaluation d''impact indépendante. Publication du rapport final + dossier carbone."}]},{"type":"kpi_grid","section_title":"📊 Indicateurs d''impact","heading_style":"teal","items":[{"value":"200","label":"Mini-grids déployés"},{"value":"80 000","label":"Ménages électrifiés"},{"value":"400","label":"Emplois créés"},{"value":"-60 %","label":"Coûts énergie PME rurales"},{"value":"15 000 T","label":"CO₂ évitées \\/ an"},{"value":"20 ans","label":"Durée de vie infrastructure"}]},{"type":"impact_tracker","section_title":"🎯 Suivi d''impact — Résultats actuels","heading_style":"teal","note":"Données au 12 mai 2026 · Phase 1 en cours · Mise à jour mensuelle","rows":[{"label":"Phase 1 — avancement","numbers":"22 % de la phase","bar_percent":22},{"label":"Mini-grids déployés","numbers":"9 \\/ 200","bar_percent":5},{"label":"Ménages électrifiés","numbers":"3 600 \\/ 80 000","bar_percent":5},{"label":"Techniciens formés","numbers":"18 \\/ 400","bar_percent":5},{"label":"CO₂ évitées (annualisées)","numbers":"1 350 T \\/ 15 000 T\\/an","bar_percent":9}]},{"type":"team","section_title":"👥 Équipe projet","members":[{"name":"[Chef de projet — à renseigner]","role":"Coordination générale · Équipe Energy"},{"name":"[Ingénieur solaire — à renseigner]","role":"Dimensionnement des mini-grids, supervision technique"},{"name":"[Expert carbone — à renseigner]","role":"Mesure CO₂, dossier valorisation · Équipe Environment"},{"name":"+ 153 volontaires actifs","role":"Terrain, installation, formation, suivi, communication"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["Banque Mondiale 2024 : Rapport accès énergie Madagascar","ADER Madagascar : Données électrification rurale par région","IRENA 2024 : Coûts solaire off-grid Afrique subsaharienne","Concept note : Disponible sur demande — projets@govgenz.org","Budget détaillé : Fichier Excel disponible sur demande PTF","Rapport pilote : À publier M+10 (décembre 2026)"]}]',
  'actif',
  'published',
  'energy,environment',
  156,
  '920 M Ar',
  'Sud & DIANA',
  '2026-02-01',
  36,
  22,
  '⚡ Énergie Solaire Communautaire',
  'Énergie Solaire Communautaire — 200 mini-grids solaires en zones isolées. GoV Gen Z Madagascar.',
'2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'energie-solaire',
  'en',
  'energie-solaire',
  '⚡ Community Solar Energy',
  '200 solar mini-grids in isolated areas to create local jobs and reduce CO₂ emissions in a measurable way.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 The challenge","heading_style":"warm","intro":"Electrification rates remain low; isolated rural areas depend on expensive, polluting diesel generators. Reliable clean power unlocks clinics, schools, and small enterprises.","bullets":["High share of energy cost in rural SME budgets","Broken cold chains for vaccines without stable electricity","Climate exposure and need for long-lived infrastructure"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Our approach","heading_style":"teal","intro":"Each mini-grid is sized for a whole village cluster — homes, school, clinic, small shops — with local maintenance jobs.","bullets":["Pillar 1 — Mini-grid hardware: solar + batteries + low-voltage distribution + prepaid metering","Pillar 2 — Local jobs: trained village energy technicians employed by community committees","Pillar 3 — Governance & finance: mobile payments, renewal fund, annual emissions audit"],"extra_paragraphs":[]},{"type":"budget_table","section_title":"💰 Budget overview","rows":[{"poste":"Solar equipment","detail":"200 mini-grids (panels, batteries, inverters, wiring)","montant":"600 000 000","row_class":""},{"poste":"Installation","detail":"Civil works, distribution, household connections","montant":"150 000 000","row_class":""},{"poste":"TOTAL (illustrative)","detail":"","montant":"920 000 000","row_class":"total"}],"footnote":""},{"type":"kpi_grid","section_title":"📊 Impact snapshot","heading_style":"teal","items":[{"value":"200","label":"Mini-grids"},{"value":"80 000","label":"Households targeted"},{"value":"400","label":"Technician jobs"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["Concept note: on request — projets@govgenz.org"]}]',
  'actif',
  'published',
  'energy,environment',
  156,
  '920 M Ar',
  'South & DIANA',
  '2026-02-01',
  36,
  22,
  '⚡ Community Solar Energy',
  'Community Solar Energy — 200 solar mini-grids in isolated areas for local jobs and measurable CO₂ reductions. GoV Gen Z Madagascar.',
'2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'acces-justice',
  'fr',
  'acces-justice',
  '⚖️ Accès à la Justice — Jeunes',
  '500 jeunes paralegals formés et 20 centres d''aide juridique gratuite dans les zones reculées pour garantir l''accès à la justice.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 Le problème","heading_style":"warm","intro":"À Madagascar, la justice est structurellement inaccessible pour la majorité. 76 % des citoyens n''ont jamais consulté un professionnel juridique, faute de proximité géographique, de coût, ou de barrières linguistiques. Les jeunes, les femmes et les ruraux sont les plus exposés aux abus sans recours.","bullets":["76 % des Malgaches sans accès à un conseiller juridique (PNUD 2024)","1 avocat pour 50 000 habitants hors Antananarivo","Délais judiciaires moyens de 3-5 ans en première instance","Les fonciers non titrés représentent 80 % des litiges ruraux non résolus","Taux de récidive carcérale à 58 % — absence de suivi post-peine"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Notre solution","heading_style":"teal","intro":"Accès à la Justice — Jeunes déploie une infrastructure juridique de proximité — des paralegals formés dans chaque commune prioritaire et des centres physiques pour les cas complexes. Simple, accessible, en malgache.","bullets":["Pilier 1 — Formation paralegals : 500 jeunes paralegals formés en 3 mois (droits fondamentaux, procédures administratives, médiation foncière), déployés dans leur commune d''origine","Pilier 2 — Centres d''aide juridique : 20 centres physiques dans les chefs-lieux de district les plus défavorisés, staffés par un juriste GoV Gen Z + paralegals locaux, consultation gratuite","Pilier 3 — Outils numériques : Application \\"Zo Malgache\\" (droits en malgache), ligne SMS de première orientation juridique, base de données jurisprudence locale"],"extra_paragraphs":["Les paralegals ne remplacent pas les avocats — ils orientent, accompagnent les démarches administratives, et réfèrent aux juristes pour les cas complexes."]},{"type":"budget_table","section_title":"💰 Budget détaillé","rows":[{"poste":"Formation paralegals","detail":"500 paralegals × 3 mois + formateurs juristes, matériel pédagogique","montant":"70 000 000","row_class":""},{"poste":"Centres d''aide juridique","detail":"20 centres — loyer 2 ans, mobilier, équipement bureautique","montant":"60 000 000","row_class":""},{"poste":"Application Zo Malgache","detail":"Développement, contenu juridique malgache, maintenance 2 ans","montant":"30 000 000","row_class":""},{"poste":"Ligne SMS orientation","detail":"Infrastructure SMS, opérateur, 24 mois de service","montant":"15 000 000","row_class":""},{"poste":"Juristes référents","detail":"4 juristes GoV Gen Z à mi-temps × 24 mois","montant":"12 000 000","row_class":""},{"poste":"Suivi & évaluation","detail":"Monitoring terrain, rapport d''impact semestriel, audit","montant":"8 000 000","row_class":""},{"poste":"TOTAL","detail":"","montant":"195 000 000","row_class":"total"}],"footnote":"Financement visé : PNUD Madagascar, USAID, Open Society Foundations. Dossier en cours de validation GoV Gen Z — décision prévue Q3 2026."},{"type":"timeline","section_title":"📅 Calendrier","phases":[{"phase_label":"Phase 0","duration":"Maintenant – 3 mois","step_title":"Validation & préparation","body":"Finalisation du dossier de validation GoV Gen Z. Identification des 20 sites prioritaires. Recrutement des juristes référents. Partenariats universités de droit."},{"phase_label":"Phase 1","duration":"M+3 – M+12","step_title":"Pilote — 200 paralegals + 8 centres","body":"Première cohorte de 200 paralegals formés et déployés. Ouverture des 8 premiers centres dans les districts pilotes. Lancement de l''application Zo Malgache. Rapport public M+12."},{"phase_label":"Phase 2","duration":"M+12 – M+24","step_title":"Extension — 300 paralegals + 12 centres","body":"Formation des 300 paralegals restants. Ouverture des 12 derniers centres. Évaluation d''impact indépendante. Publication rapport final."}]},{"type":"kpi_grid","section_title":"📊 Indicateurs d''impact","heading_style":"teal","items":[{"value":"500","label":"Paralegals formés"},{"value":"20","label":"Centres d''aide juridique"},{"value":"50 000","label":"Consultations prévues \\/ an"},{"value":"114 districts","label":"Couverture nationale"},{"value":"Gratuit","label":"Toutes consultations"},{"value":"100 %","label":"En langue malgache"}]},{"type":"note_panel","section_title":"🎯 Suivi d''impact","heading_style":"teal","message":"📊 Le suivi d''impact sera activédès le démarrage officiel du projet. Statut actuel : en cours de validation","submessage":""},{"type":"team","section_title":"👥 Équipe projet","members":[{"name":"[Chef de projet — à renseigner]","role":"Coordination générale · Équipe Legal"},{"name":"[Juriste principal — à renseigner]","role":"Conception curriculum, formation paralegals, référent cas complexes"},{"name":"[Lead tech — à renseigner]","role":"Application Zo Malgache · Équipe Digital"},{"name":"+ 64 volontaires actifs","role":"Terrain, orientation juridique, communication, suivi"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["PNUD 2024 : Rapport accès à la justice Madagascar","Ministère de la Justice 2025 : Données densité juridique par région","Baromètre Gouvernance 2024 : Perception de la justice par les jeunes","Concept note : Disponible sur demande — projets@govgenz.org","Budget détaillé : Fichier Excel disponible sur demande PTF","Décision validation : Prévue Q3 2026"]}]',
  'validation',
  'draft',
  'legal,citizen',
  67,
  '195 M Ar',
  'National',
  '2026-03-01',
  24,
  5,
  '⚖️ Accès à la Justice — Jeunes',
  'Accès à la Justice — Jeunes — 500 paralegals et 20 centres d''aide juridique. GoV Gen Z Madagascar.',
NULL,
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'acces-justice',
  'en',
  'acces-justice',
  '⚖️ Access to Justice — Youth',
  '500 trained youth paralegals and 20 free legal aid centres in remote areas to improve access to justice.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 The challenge","heading_style":"warm","intro":"Justice services are often physically and financially out of reach. Young people, women, and rural communities face disputes without guidance.","bullets":["Very few lawyers per capita outside the capital","Long case backlogs","Land and administrative disputes with no first-line support"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Our approach","heading_style":"teal","intro":"Train young paralegals for first-line orientation and mediation, backed by physical aid centres and a simple rights app in Malagasy.","bullets":["Pillar 1 — Paralegal training: 500 youth, 3-month curriculum (rights, admin procedures, land mediation)","Pillar 2 — Aid centres: 20 district hubs with a staff lawyer + local paralegals, free intake","Pillar 3 — Digital tools: “Zo Malgache” app, SMS triage line, local case-law notes"],"extra_paragraphs":[]},{"type":"budget_table","section_title":"💰 Budget overview","rows":[{"poste":"Paralegal training","detail":"500 × 3 months + trainers","montant":"70 000 000","row_class":""},{"poste":"Aid centres","detail":"20 centres, 24-month rent and equipment","montant":"60 000 000","row_class":""},{"poste":"TOTAL (illustrative)","detail":"","montant":"195 000 000","row_class":"total"}],"footnote":""},{"type":"note_panel","section_title":"🎯 Impact tracking","heading_style":"teal","message":"📊 Impact tracking will startonce validation is complete. Current status: under validation","submessage":""},{"type":"sources","section_title":"📎 Sources & documents","lines":["Concept note: on request — projets@govgenz.org"]}]',
  'validation',
  'draft',
  'legal,citizen',
  67,
  '195 M Ar',
  'National',
  '2026-03-01',
  24,
  5,
  '⚖️ Access to Justice — Youth',
  'Access to Justice — Youth: 500 trained paralegals and 20 free legal aid centres in remote areas. GoV Gen Z Madagascar.',
NULL,
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'sante-maternelle',
  'fr',
  'sante-maternelle',
  '🏥 Santé Maternelle+',
  'Renforcer 100 cliniques rurales pour réduire la mortalité maternelle de 40 % en 3 ans — équipements, formations, protocoles.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 Le problème","heading_style":"warm","intro":"Madagascar affiche l''un des taux de mortalité maternelle les plus élevés au monde. 478 décès pour 100 000 naissances vivantes — contre une moyenne de 196 en Afrique subsaharienne. Dans ATSIMO ANDREFANA, ce chiffre dépasse les 700. La plupart de ces décès sont évitables.","bullets":["478\\/100 000 taux mortalité maternelle national (OMS 2024)","700+\\/100 000 dans ATSIMO ANDREFANA — région cible","Seulement 44 % des accouchements assistés par personnel qualifié (Ministère Santé 2025)","72 % des cliniques rurales sans équipement obstétrical minimal","Chaîne du froid brisée dans 60 % des centres de santé ruraux"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Notre solution","heading_style":"teal","intro":"Santé Maternelle+ adopte une approche systémique : équiper, former, protocolariser. Pas de matériel sans formation, pas de formation sans suivi de protocoles. Chaque clinique renforcée devient un centre de référence pour son district.","bullets":["Pilier 1 — Équipement des cliniques : Kits obstétricaux standardisés, réfrigérateurs solaires pour chaîne du froid vaccins, oxygène médical, tables d''accouchement, lampes chirurgicales","Pilier 2 — Formation des sages-femmes : 300 sages-femmes formées aux urgences obstétricales (SOUB), protocoles hémorragie post-partum, pré-éclampsie, dystocie — formations mensuelles en cascade","Pilier 3 — Protocoles & référencement : Guides de protocoles illustrés en malgache, système de référencement SMS vers hôpitaux de district, tableau de bord mortalité par clinique"],"extra_paragraphs":["Un suivi mensuel des indicateurs par clinique permet d''identifier rapidement les problèmes et d''adapter les formations en temps réel."]},{"type":"budget_table","section_title":"💰 Budget détaillé","rows":[{"poste":"Équipement cliniques","detail":"100 kits obstétricaux + réfrigérateurs solaires + consommables","montant":"380 000 000","row_class":""},{"poste":"Formation sages-femmes","detail":"300 sages-femmes × 5 jours SOUB + formations continues","montant":"120 000 000","row_class":""},{"poste":"Protocoles & guides","detail":"Conception, impression 2 000 guides malgache + français","montant":"30 000 000","row_class":""},{"poste":"Chaîne du froid","detail":"100 réfrigérateurs solaires + installation + maintenance 3 ans","montant":"150 000 000","row_class":""},{"poste":"Système SMS référencement","detail":"Infrastructure SMS, formation personnels, 36 mois service","montant":"40 000 000","row_class":""},{"poste":"Suivi & évaluation","detail":"Tableau de bord mortalité, audits trimestriels, rapport final","montant":"60 000 000","row_class":""},{"poste":"TOTAL","detail":"","montant":"780 000 000","row_class":"total"}],"footnote":"Financement visé : UNFPA, OMS Madagascar, Union Européenne (santé reproductive). Partenariats Médecins du Monde et MSF pour les formations SOUB."},{"type":"timeline","section_title":"📅 Calendrier","phases":[{"phase_label":"Phase 1","duration":"0 – 10 mois","step_title":"Pilote — 30 cliniques, districts prioritaires","body":"Sélection des 30 cliniques les plus critiques. Livraison et installation des équipements. Formation de 90 sages-femmes en SOUB. Mesure des données de référence pour comparaison d''impact. Rapport public M+10."},{"phase_label":"Phase 2","duration":"10 – 24 mois","step_title":"Extension — 50 cliniques supplémentaires","body":"Déploiement vers les 50 cliniques suivantes. Formation de 150 sages-femmes. Lancement du tableau de bord mortalité public. Publication rapport intermédiaire."},{"phase_label":"Phase 3","duration":"24 – 36 mois","step_title":"Finalisation — 20 cliniques restantes + évaluation","body":"Renforcement des 20 dernières cliniques. Formation des 60 sages-femmes restantes. Évaluation d''impact indépendante. Publication rapport final + recommandations politiques pour réplication nationale."}]},{"type":"kpi_grid","section_title":"📊 Indicateurs d''impact","heading_style":"teal","items":[{"value":"100","label":"Cliniques renforcées"},{"value":"300","label":"Sages-femmes formées"},{"value":"-40 %","label":"Mortalité maternelle visée"},{"value":"25 000","label":"Accouchements sécurisés \\/ an"},{"value":"100 %","label":"Chaîne du froid assurée"},{"value":"Mensuel","label":"Rapport mortalité public"}]},{"type":"impact_tracker","section_title":"🎯 Suivi d''impact — Résultats actuels","heading_style":"teal","note":"Données au 12 mai 2026 · Phase 1 en cours · Mise à jour mensuelle","rows":[{"label":"Phase 1 — avancement","numbers":"18 % de la phase","bar_percent":18},{"label":"Cliniques renforcées","numbers":"6 \\/ 100","bar_percent":6},{"label":"Sages-femmes formées (SOUB)","numbers":"16 \\/ 300","bar_percent":5},{"label":"Réduction mortalité (zones pilotes)","numbers":"−8 % \\/ obj. −40 %","bar_percent":20},{"label":"Chaîne du froid opérationnelle","numbers":"6 \\/ 100 cliniques","bar_percent":6}]},{"type":"team","section_title":"👥 Équipe projet","members":[{"name":"[Chef de projet — à renseigner]","role":"Coordination générale · Équipe Health"},{"name":"[Médecin référent — à renseigner]","role":"Supervision médicale, protocoles SOUB, formation sages-femmes"},{"name":"[Coordinateur terrain — à renseigner]","role":"Logistique équipements, suivi cliniques · Équipe Territories"},{"name":"+ 109 volontaires actifs","role":"Terrain, logistique, formation, suivi indicateurs, communication"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["OMS 2024 : Tendances mortalité maternelle 2000-2023","Ministère de la Santé Madagascar 2025 : Rapport santé maternelle et néonatale","UNFPA Madagascar : État des centres de santé materno-infantile","Concept note : Disponible sur demande — projets@govgenz.org","Budget détaillé : Fichier Excel disponible sur demande PTF","Rapport pilote : À publier M+10 (février 2027)"]}]',
  'actif',
  'published',
  'health,territories',
  112,
  '780 M Ar',
  'ATSIMO ANDREFANA',
  '2026-04-01',
  36,
  18,
  '🏥 Santé Maternelle+',
  'Santé Maternelle+ — Renforcer 100 cliniques rurales pour réduire la mortalité maternelle de 40 %. GoV Gen Z Madagascar.',
'2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

INSERT INTO project_projects (slug, locale, translation_group, title, excerpt, body, body_content_mode, body_blocks, project_status, publication_state, sectors_csv, volunteers_count, budget_display, geography, launched_at, duration_months, progress_percent, meta_title, meta_description, published_at, created_at, updated_at, deleted_at) VALUES (
  'sante-maternelle',
  'en',
  'sante-maternelle',
  '🏥 Maternal Health+',
  'Strengthen 100 rural clinics to reduce maternal mortality by 40% in three years — equipment, training, protocols.',
  NULL,
  'blocks',
  '[{"type":"section_rich","heading":"📰 The challenge","heading_style":"warm","intro":"Maternal mortality remains critically high; many deaths are preventable with basic equipment, protocols, and referral. Rural clinics lack minimal obstetric kits and reliable cold chains for vaccines.","bullets":["Low share of births attended by skilled staff in remote areas","Weak cold chain in rural health posts","Need for training, supervision, and monthly indicators"],"extra_paragraphs":[]},{"type":"section_rich","heading":"✅ Our approach","heading_style":"teal","intro":"A systemic model: equip, train, protocolise. No equipment roll-out without training; no training without follow-up.","bullets":["Pillar 1 — Clinic equipment: standard obstetric kits, solar fridges, oxygen where needed","Pillar 2 — Midwife training: emergencies (PPH, pre-eclampsia), monthly cascade sessions","Pillar 3 — Protocols & referral: illustrated Malagasy guides, SMS referral to district hospitals, public dashboard"],"extra_paragraphs":[]},{"type":"budget_table","section_title":"💰 Budget overview","rows":[{"poste":"Clinic equipment","detail":"100 kits + solar fridges + consumables","montant":"380 000 000","row_class":""},{"poste":"Midwife training","detail":"300 midwives × 5-day emergency course","montant":"120 000 000","row_class":""},{"poste":"TOTAL (illustrative)","detail":"","montant":"780 000 000","row_class":"total"}],"footnote":""},{"type":"kpi_grid","section_title":"📊 Impact snapshot","heading_style":"teal","items":[{"value":"100","label":"Clinics"},{"value":"300","label":"Midwives trained"},{"value":"−40%","label":"MMR target (3 yrs)"}]},{"type":"sources","section_title":"📎 Sources & documents","lines":["Concept note: on request — projets@govgenz.org"]}]',
  'actif',
  'published',
  'health,territories',
  112,
  '780 M Ar',
  'ATSIMO ANDREFANA',
  '2026-04-01',
  36,
  18,
  '🏥 Maternal Health+',
  'Maternal Health+ — strengthen 100 rural clinics to cut maternal mortality by 40% in three years. GoV Gen Z Madagascar.',
'2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  '2026-05-15 15:38:36',
  NULL
);

SET FOREIGN_KEY_CHECKS = 1;
